output_path: "/scratch/indikar_root/indikar1/cstansbu/woundHealing/"
images: "config/woundPaths.txt"
channels:
    nucleus: 1
    red: 0
    green: 2
prepare:
    workers: 8
    rescale_factor: 0.5
    bitspersample: 16
preprocess:
    workers: 15
    median_rad: 2
    adaptive_hist_rad: 30
    bkgnd_rad: 60
    bitspersample: 16
stardist:
    model: '2D_versatile_fluo'
    prob_thresh: 0.4
    nms_thresh: 0.2
segmentation_movie:
    fps: 10
    dpi: 300
    height: 10
    width: 30
    seg_color: 'k'
btrack:
    path: "/home/cstansbu/BayesianTracker/"
    config: "config/trackerConfig.json"
phase:
    alpha: 0.05
    phase_map: 
        G1: "110"
        S: "111"
        G2: "011"

    
