output_path: "/scratch/indikar_root/indikar1/cstansbu/pf-test/"
images: "config/imagePaths.txt"
flattenRGB: True
downsample_scale_factor: 0.5
channels:
    nucleus: 1
    red: 0
    green: 2
preprocessing:
    bkgnd_radius: 20
    local_histogram_footprint: -1
    global_histogram_limit: -1
    median_radius: -1
stardist:
    model: '2D_versatile_fluo'
    prob_thresh: 0.4
    nms_thresh: 0.2
btrack:
    path: "/home/cstansbu/BayesianTracker/"
    config: "config/trackerConfig.json"
    
